version: '3.8'

services:

  nginx:
    image: nginx:latest
    volumes:
      - D:\Ly\Study\ITMO\Ki5\Web\Code\Chatbox\nginx\nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"  
    depends_on:
      - website
      - chat
    networks:
      - app-network

  chat:
    build:
      context: ./chat
      dockerfile: Dockerfile
    container_name: chat_server
    ports:
      - "8001:8001"  
    environment:
      - DATABASE_URL=postgresql://lyn:11032002@db:5432/chatbox
    depends_on:
      - db
    volumes:
      - ./db:/app/db  
    networks:
      - app-network

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website_server
    ports:
      - "8000:8000"  
    environment:
      - DATABASE_URL=postgresql://lyn:11032002@db:5432/chatbox
    depends_on:
      - db
    volumes:
      - ./db:/app/db  
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: lyn
      POSTGRES_PASSWORD: 11032002
      POSTGRES_DB: chatbox
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    

networks:
  app-network:
